apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-service
spec:
  selector:
    app: {{ .Values.applicationName }}
  ports:
  - port: 80
    targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP