apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jimdel
  namespace: flux-system
  annotations:
    fluxcd.io/image-policy: flux-system/jimdel
    fluxcd.io/tag.image: flux-system/jimdel
spec:
  interval: 10m
  chart:
    spec:
      chart: .helm # Path to your existing Helm chart
      version: '*'
      sourceRef:
        kind: GitRepository
        name: jimdel-source
        namespace: flux-system
      interval: 1m
  targetNamespace: jimdel # Changed from default to jimdel
  install:
    createNamespace: true
  upgrade:
    force: true  # Force Helm upgrades even when chart or values haven't changed
    remediation:
      retries: 3
  values:
    image:
      repository: delayj/jimdel
      tag: "main-19918b7e92f43866ecbc5ce8d68aa38e38ffca1f" # This will be updated by Flux based on ImagePolicy
      pullPolicy: Always
    podAnnotations:
      rollme: {{ now | quote }}  # This annotation changes each time, forcing a restart
