apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jimdel
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jimdel
  policy:
    semver:
      range: '>=0.0.0'