apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jimdel
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jimdel
  policy:
    regex:
      pattern: '^main-[a-f0-9]+$' # Match tags like 'main-<commit-sha>'