apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel-metrics
  namespace: cloudflare-tunnel
  labels:
    app: cloudflare-tunnel
spec:
  ports:
  - name: metrics
    port: 2000
    protocol: TCP
    targetPort: 2000
  selector:
    app: cloudflare-tunnel
