apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jimdel-source
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jimdel/pi-cluster-config.git
  ref:
    branch: main