apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.applicationName }}-certmanager
spec:
  acme:
    email: {{ .Values.certmanager.contactEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.applicationName }}-certmanager--key
    solvers:
    - http01:
        ingress:
          class: traefik
