apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "23.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    server:
      persistentVolume:
        enabled: true
        size: 8Gi
    alertmanager:
      persistentVolume:
        enabled: true
        size: 2Gi
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    pushgateway:
      enabled: true
    configmapReload:
      prometheus:
        enabled: true
