apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system